export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAILURE = "AUTH_FAILURE"
export const AUTH_ERROR = "AUTH_ERROR"
export const TOKEN_EXPIRED = "AUTH_FAILURE"
export const AUTH_LOGOUT = "AUTH_LOGOUT"

export const USER_LIST_ACCESS = "USER_LIST_ACCESS"
export const USER_LIST_FULL = "USER_LIST_FULL"
export const USER_LIST_EMPTY = "USER_LIST_EMPTY"
export const USER_LIST_ERROR = "USER_LIST_ERROR"

export const USER_REMOVE_ACCESS = "USER_REMOVE_ACCESS"
export const USER_REMOVE_SUCCESS = "USER_REMOVE_SUCCESS"
export const USER_REMOVE_ERROR = "USER_LIST_EMPTY"

export const FILE_ACCESS = "FILE_ACCESS"

export const FILE_UP_ACCESS = "FILE_UP_ACCESS"
export const FILE_UP_SUCCESS = "FILE_UP_UPLOAD"
export const FILE_UP_FAILURE = "FILE_UP_FAILED"
export const FILE_UP_ERROR = "FILE_UP_FAILED"

export const CRND_ACCESS = "CONTRACT_REF_NO_AND_DESC_ACCESS"
export const CRND_SUCCESS = "CONTRACT_REF_NO_AND_DESC_SUCCESS"
export const CRND_FAILURE = "CONTRACT_REF_NO_AND_DESC_FAILURE"
export const CRND_ERROR = "CONTRACT_REF_NO_AND_DESC_ERROR"

export const CTL_SUCCESS = "COMMODITY_TYPE_LIST_SUCCESS"
export const CTL_FAILURE = "COMMODITY_TYPE_LIST_FAILURE"
export const CTL_ERROR = "COMMODITY_TYPE_LIST_ERROR"

export const VNLS_SUCCESS = "VENDOR_NAME_LIST_SERVICE_SUCCESS"
export const VNLS_FAILURE = "ENDOR_NAME_LIST_SERVICE_FAILURE"
export const VNLS_ERROR = "ENDOR_NAME_LIST_SERVICE_ERROR"

export const IBS_ACCESS = "ITEM_BASED_SEARCH_ACCESS"
export const IBS_SUCCESS = "ITEM_BASED_SEARCH_SUCCESS"
export const IBS_FAILURE = "ITEM_BASED_SEARCH_FAILURE"
export const IBS_ERROR = "ITEM_BASED_SEARCH_ERROR"

export const RPR_ACCESS = "PURCHASE_REQUEST_ACCESS"
export const RPR_SUCCESS = "PURCHASE_REQUEST_SUCCESS"
export const RPR_FAILURE = "PURCHASE_REQUEST_FAILURE"
export const RPR_ERROR = "PURCHASE_REQUEST_ERROR"



export const UPLOAD_EXTERNAL_ACCESS = "UPLOAD_EXTERNAL_ACCESS"
export const UPLOAD_EXTERNAL_SUCCESS = "UPLOAD_EXTERNAL_SUCCESS"
export const UPLOAD_EXTERNAL_FAILURE = "UPLOAD_EXTERNAL_FAILURE"
export const UPLOAD_EXTERNAL_ERROR = "UPLOAD_EXTERNAL_ERROR"



export const UPLOAD_ACCESS= "UPLOAD_ACCESS"
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS"
export const UPLOAD_FAILURE = "UPLOAD_FAILURE"
export const UPLOAD_ERROR = "UPLOAD_ERROR"



export const UPLOAD_DEL_ACCESS = "FILE_DELETE_ACCESS"
export const UPLOAD_DEL_SUCCESS = "USER_REMOVE_SUCCESS"
export const UPLOAD_DEL_FAILURE = "USER_REMOVE_FAILURE"
export const UPLOAD_DEL_ERROR = "FILE_FAILED"

export const FTPC_ACCESS = "FUND_TYPE_PERSON_CODE_PROJECT_ACCESS"
export const FTPC_SUCCESS = "FUND_TYPE_PERSON_CODE_PROJECT_SUCCESS"
export const FTPC_SUCCESS_L1 = "FUND_TYPE_PERSON_CODE_PROJECT_L1_SUCCESS"
export const FTPC_SUCCESS_L2 = "FUND_TYPE_PERSON_CODE_PROJECT_L2_SUCCESS"
export const FTPC_SUCCESS_L3 = "FUND_TYPE_PERSON_CODE_PROJECT_L3_SUCCESS"
export const FTPC_SUCCESS_L4 = "FUND_TYPE_PERSON_CODE_PROJECT_L4_SUCCESS"
export const FTPC_SUCCESS_L5 = "FUND_TYPE_PERSON_CODE_PROJECT_L5_SUCCESS"
export const FTPC_SUCCESS_L6 = "FUND_TYPE_PERSON_CODE_PROJECT_L6_SUCCESS"
export const FTPC_SUCCESS_L7 = "FUND_TYPE_PERSON_CODE_PROJECT_L7_SUCCESS"
export const FTPC_SUCCESS_L8 = "FUND_TYPE_PERSON_CODE_PROJECT_L8_SUCCESS"
export const FTPC_SUCCESS_L9 = "FUND_TYPE_PERSON_CODE_PROJECT_L9_SUCCESS"
export const FTPC_FAILURE = "FUND_TYPE_PERSON_CODE_PROJECT_FAILURE"
export const FTPC_ERROR = "FUND_TYPE_PERSON_CODE_PROJECT_ERROR"

export const ADDRESS_ACCESS = "ADDRESS_ACCESS"
export const ADDRESS_SUCCESS = "ADDRESS_SUCCESS"
export const ADDRESS_FAILURE = "ADDRESS_FAILURE"
export const ADDRESS_ERROR = "ADDRESS_ERROR"

export const DELIVERY_ADDRESS_ACCESS = "DELIVERY_ADDRESS_ACCESS"
export const DELIVERY_ADDRESS_SUCCESS = "DELIVERY_ADDRESS_SUCCESS"
export const DELIVERY_ADDRESS_FAILURE = "DELIVERY_ADDRESS_FAILURE"
export const DELIVERY_ADDRESS_ERROR = "DELIVERY_ADDRESS_ERROR"

export const CCC_ACCESS = "COST_CENTRE_CODE_ACTION_ACCESS"
export const CCC_SUCCESS = "COST_CENTRE_CODE_ACTION_SUCCESS"
export const CCC_FAILURE = "COST_CENTRE_CODE_ACTION_FAILURE"
export const CCC_ERROR = "COST_CENTRE_CODE_ACTION_ERROR"

export const SEGMENTATION_ACCESS = "SEGMENTATION_ACCESS"
export const SEGMENTATION_SUCCESS = "SEGMENTATION_SUCCESS"
export const SEGMENTATION_FAILURE = "SEGMENTATION_FAILURE"
export const SEGMENTATION_ERROR = "SEGMENTATION_ERROR"

export const PRI_ACCESS = "PURCHASE_REQUEST_ITEM_DETAILS_ACCESS"
export const PRI_SUCCESS = "PURCHASE_REQUEST_ITEM_DETAILS_SUCCESS"
export const PRI_FAILURE = "PURCHASE_REQUEST_ITEM_DETAILS_FAILURE"
export const PRI_ERROR = "PURCHASE_REQUEST_ITEM_DETAILS_ERROR"

export const PRI_ACCESS_POPUP = "PURCHASE_REQUEST_ITEM_DETAILS_ACCESS_POPUP"
export const PRI_SUCCESS_POPUP = "PURCHASE_REQUEST_ITEM_DETAILS_SUCCESS_POPUP"
export const PRI_FAILURE_POPUP = "PURCHASE_REQUEST_ITEM_DETAILS_FAILURE_POPUP"
export const PRI_ERROR_POPUP = "PURCHASE_REQUEST_ITEM_DETAILS_ERROR_POPUP"

export const PRI_NCACCESS_POPUP = "PURCHASE_REQUEST_ITEM_DETAILS_ACCESS_NON_CONTRACT_POPUP"
export const PRI_NCSUCCESS_POPUP = "PURCHASE_REQUEST_ITEM_DETAILS_SUCCESS_NON_CONTRACT_POPUP"
export const PRI_NCFAILURE_POPUP = "PURCHASE_REQUEST_ITEM_DETAILS_FAILURE_NON_CONTRACT_POPUP"
export const PRI_NCERROR_POPUP = "PURCHASE_REQUEST_ITEM_DETAILS_ERROR_NON_CONTRACT_POPUP"

export const PRI_FFACCESS_POPUP = "PURCHASE_REQUEST_ITEM_DETAILS_ACCESS_FREE_FORM_POPUP"
export const PRI_FFSUCCESS_POPUP = "PURCHASE_REQUEST_ITEM_DETAILS_SUCCESS_FREE_FORM_POPUP"
export const PRI_FFFAILURE_POPUP = "PURCHASE_REQUEST_ITEM_DETAILS_FAILURE_FREE_FORM_POPUP"
export const PRI_FFERROR_POPUP = "PURCHASE_REQUEST_ITEM_DETAILS_ERROR_FREE_FORM_POPUP"


export const CD_ACCESS = "CATELOGUE_DROPDOWN_ACCESS"
export const CD_SUCCESS = "CATELOGUE_DROPDOWN_SUCCESS"
export const CD_FAILURE = "CATELOGUE_DROPDOWN_FAILURE"
export const CD_ERROR = "CATELOGUE_DROPDOWN_ERROR"

export const BCS_ACCESS = "BUYER_CATELOGUE_SEARCH_ACCESS"
export const BCS_SUCCESS = "BUYER_CATELOGUE_SEARCH_SUCCESS"
export const BCS_FAILURE = "BUYER_CATELOGUE_SEARCH_FAILURE"
export const BCS_ERROR = "BUYER_CATELOGUE_SEARCH_ERROR"

export const SPRL_ACCESS = "SEARCH_PRODUCT_LIST_ACCESS"
export const SPRL_SUCCESS = "SEARCH_PRODUCT_LIST_SUCCESS"
export const SPRL_FAILURE = "SEARCH_PRODUCT_LIST_FAILURE"
export const SPRL_ERROR = "SEARCH_PRODUCT_LIST_ERROR"

export const SPRCL_ACCESS = "SEARCH_PRODUCT_CANCEL_LIST_ACCESS"
export const SPRCL_SUCCESS = "SEARCH_PRODUCT_CANCEL_LIST_SUCCESS"
export const SPRCL_FAILURE = "SEARCH_PRODUCT_CANCEL_LIST_FAILURE"
export const SPRCL_ERROR = "SEARCH_PRODUCT_CANCEL_LIST_ERROR"

export const PR_ACCESS = "PRODUCT_REQUEST_ACCESS"
export const PR_SUCCESS = "PRODUCT_REQUEST_SUCCESS"
export const PR_FAILURE = "PRODUCT_REQUEST_FAILURE"
export const PR_ERROR = "PRODUCT_REQUEST_ERROR"

export const IGRN_ACCESS = "ISSUE_GRN_ACCESS"
export const IGRN_SUCCESS = "ISSUE_GRN_SUCCESS"
export const IGRN_FAILURE = "ISSUE_GRN_FAILURE"
export const IGRN_ERROR = "ISSUE_GRN_ERROR"

export const GRNL_ACCESS = "GRN_LISTING_ACCESS"
export const GRNL_SUCCESS = "GRN_LISTING_SUCCESS"
export const GRNL_FAILURE = "GRN_LISTING_FAILURE"
export const GRNL_ERROR = "GRN_LISTING_ERROR"

export const SPR_ACCESS = "SAVE_PURCHASE_REQUEST_ACCESS"
export const SPR_SUCCESS = "SAVE_PURCHASE_REQUEST_SUCCESS"
export const SPR_FAILURE = "SAVE_PURCHASE_REQUEST_FAILURE"
export const SPR_ERROR = "SAVE_PURCHASE_REQUEST_ERROR"

export const MENU_ACCESS = "MENU_ACCESS"
export const MENU_SUCCESS = "MENU__SUCCESS"
export const MENU_FAILURE = "MENU_FAILURE"
export const MENU_ERROR = "MENU_ERROR"

export const GRND_ACCESS = "GRND_ACCESS"
export const GRND_SUCCESS = "GRND__SUCCESS"
export const GRND_FAILURE = "GRND_FAILURE"
export const GRND_ERROR = "GRND_ERROR"

export const SPRA_ACCESS = "SPRA_ACCESS"
export const SPRA_SUCCESS = "SPRA_SUCCESS"
export const SPRA_FAILURE = "SPRA_FAILURE"
export const SPRA_ERROR = "SPRA_ERROR"

export const PRRS_ACCESS = "PRRS_ACCESS"
export const PRRS_SUCCESS = "PRRS_SUCCESS"
export const PRRS_FAILURE = "PRRS_FAILURE"
export const PRRS_ERROR = "PRRS_ERROR"

export const VIEW_SPR_ACCESS = "VIEW_SPR_ACCESS"
export const VIEW_SPR_SUCCESS = "VIEW_SPR_SUCCESS"
export const VIEW_SPR_FAILURE = "VIEW_SPR_FAILURE"
export const VIEW_SPR_ERROR = "VIEW_SPR_ERROR"

export const APR_ACCESS = "APR_ACCESS"
export const APR_SUCCESS = "APR_SUCCESS"
export const APR_FAILURE = "APR_FAILURE"
export const APR_ERROR = "APR_ERROR"

export const POP_ACCESS = "POP_ACCESS"
export const POP_SUCCESS = "POP_SUCCESS"
export const POP_FAILURE = "POP_FAILURE"
export const POP_ERROR = "POP_ERROR"

export const POL_ACCESS = "POL_ACCESS"
export const POL_SUCCESS = "POL_SUCCESS"
export const POL_FAILURE = "POL_FAILURE"
export const POL_ERROR = "POL_ERROR"

export const VPO_ACCESS = "VPO_ACCESS"
export const VPO_SUCCESS = "VPO_SUCCESS"
export const VPO_FAILURE = "VPO_FAILURE"
export const VPO_ERROR = "VPO_ERROR"

export const AR_ACCESS = "AR_ACCESS"
export const AR_SUCCESS = "AR_SUCCESS"
export const AR_FAILURE = "AR_FAILURE"
export const AR_ERROR = "AR_ERROR"

export const GDS_ACCESS = "GDS_ACCESS"
export const GDS_SUCCESS = "GDS_SUCCESS"
export const GDS_FAILURE = "GDS_FAILURE"
export const GDS_ERROR = "GDS_ERROR"


export const GVDC_ACCESS = "GVDC_ACCESS"
export const GVDC_SUCCESS = "GVDC_SUCCESS"
export const GVDC_FAILURE = "GVDC_FAILURE"
export const GVDC_ERROR = "GVDC_ERROR"

export const GDL_ACCESS = "GDL_ACCESS"
export const GDL_SUCCESS = "GDL_SUCCESS"
export const GDL_FAILURE = "GDL_FAILURE"
export const GDL_ERROR = "GDL_ERROR"

export const SDO_ACCESS = "SDO_ACCESS"
export const SDO_SUCCESS = "SDO_SUCCESS"
export const SDO_FAILURE = "SDO_FAILURE"
export const SDO_ERROR = "SDO_ERROR"

export const FILE_UPLOAD = "FILE_UPLOAD"
export const FILE_FILED = "FILE_FILED"

export const DOWNLOAD_ACCESS = "DOWNLOAD_ACCESS"
export const DOWNLOAD_SUCCESS = "DOWNLOAD_SUCCESS"
export const DOWNLOAD_FAILURE = "DOWNLOAD_FAILURE"
export const DOWNLOAD_ERROR = "DOWNLOAD_ERROR"

export const DELETE_ACCESS = "DELETE_ACCESS"
export const DELETE_SUCCESS = "DELETE_SUCCESS"
export const DELETE_FAILURE = "DELETE_FAILURE"
export const DELETE_ERROR = "DELETE_ERROR"

export const DELETE_EXTERNAL_ACCESS = "DELETE_EXTERNAL_ACCESS"
export const DELETE_EXTERNAL_SUCCESS = "DELETE_EXTERNAL_SUCCESS"
export const DELETE_EXTERNAL_FAILURE = "DELETE_EXTERNAL_FAILURE"
export const DELETE_EXTERNAL_ERROR = "DELETE_EXTERNAL_ERROR"



export const GRNS_ACCESS = "GRNS_ACCESS"
export const GRNS_SUCCESS = "GRNS_SUCCESS"
export const GRNS_FAILURE = "GRNS_FAILURE"
export const GRNS_ERROR = "GRNS_ERROR"

export const INVISUE_ACCESS = "INVISUE_ACCESS"
export const INVISUE_SUCCESS = "INVISUE_SUCCESS"
export const INVISUE_FAILURE = "INVISUE_FAILURE"
export const INVISUE_ERROR = "INVISUE_ERROR"

export const INVILIST_ACCESS = "INVILIST_ACCESS"
export const INVILIST_SUCCESS = "INVILIST_SUCCESS"
export const INVILIST_FAILURE = "INVILIST_FAILURE"
export const INVILIST_ERROR = "INVILIST_ERROR"

export const VIEWINV_ACCESS = "VIEWINV_ACCESS"
export const VIEWINV_SUCCESS = "VIEWINV_SUCCESS"
export const VIEWINV_FAILURE = "VIEWINV_FAILURE"
export const VIEWINV_ERROR = "VIEWINV_ERROR"

export const IS_ACCESS = "IS_ACCESS"
export const IS_SUCCESS = "IS_SUCCESS"
export const IS_FAILURE = "IS_FAILURE"
export const IS_ERROR = "IS_ERROR"

export const RISEARCH_ACCESS = "RISEARCH_ACCESS"
export const RISEARCH_SUCCESS = "RISEARCH_SUCCESS"
export const RISEARCH_VERIFIED_SUCCESS = "RISEARCH_VERIFIED_SUCCESS"
export const RISEARCH_FAILURE = "RISEARCH_FAILURE"
export const RISEARCH_ERROR = "RISEARCH_ERROR"

export const VIDC_ACCESS = "VIDC_ACCESS"
export const VIDC_SUCCESS = "VIDC_SUCCESS"
export const VIDC_FAILURE = "VIDC_FAILURE"
export const VIDC_ERROR = "VIDC_ERROR"

export const IN_SAVE_ACCESS = "IN_SAVE_ACCESS"
export const IN_SAVE_SUCCESS = "IN_SAVE_SUCCESS"
export const IN_SAVE_FAILURE = "IN_SAVE_FAILURE"
export const IN_SAVE_ERROR = "IN_SAVE_ERROR"

export const IV_ACCESS = "IV_ACCESS"
export const IV_SUCCESS = "IV_SUCCESS"
export const IV_FAILURE = "IV_FAILURE"
export const IV_ERROR = "IV_ERROR"

export const IVH_ACCESS = "IV_ACCESS"
export const IVH_SUCCESS = "IV_SUCCESS"
export const IVH_FAILURE = "IV_FAILURE"
export const IVH_ERROR = "IV_ERROR"

export const SUBINV_ACCESS = "SUBINV_ACCESS"
export const SUBINV_SUCCESS = "SUBINV_SUCCESS"
export const SUBINV_FAILURE = "SUBINV_FAILURE"
export const SUBINV_ERROR = "SUBINV_ERROR"

export const GFA_ACCESS = "GFA_ACCESS"
export const GFA_SUCCESS = "GFA_SUCCESS"
export const GFA_FAILURE = "GFA_FAILURE"
export const GFA_ERROR = "GFA_ERROR"

export const GAO_ACCESS = "GAO_ACCESS"
export const GAO_SUCCESS = "GAO_SUCCESS"
export const GAO_FAILURE = "GAO_FAILURE"
export const GAO_ERROR = "GAO_ERROR"

export const GAPL_ACCESS = "GAPL_ACCESS"
export const GAPL_SUCCESS = "GAPL_SUCCESS"
export const GAPL_FAILURE = "GAPL_FAILURE"
export const GAPL_ERROR = "GAPL_ERROR"

export const GFS_ACCESS = "GFS_ACCESS"
export const GFS_SUCCESS = "GFS_SUCCESS"
export const GFS_FAILURE = "GFS_FAILURE"
export const GFS_ERROR = "GAPL_ERROR"

export const GAT_ACCESS = "GAT_ACCESS"
export const GAT_SUCCESS = "GAT_SUCCESS"
export const GAT_FAILURE = "GAT_FAILURE"
export const GAT_ERROR = "GAPL_ERROR"

export const GSAP_ACCESS = "GSAP_ACCESS"
export const GSAP_SUCCESS = "GSAP_SUCCESS"
export const GSAP_FAILURE = "GSAP_FAILURE"
export const GSAP_ERROR = "GAPL_ERROR"

export const GENERAE_DOPDF_ACCESS = "GENERAE_DOPDF_ACCESS"
export const GENERAE_DOPDF_SUCCESS = "GENERAE_DOPDF_SUCCESS"
export const GENERAE_DOPDF_ERROR = "GENERAE_DOPDF_ERROR"

export const GENERAE_PRPDF_ACCESS = "GENERAE_PRPDF_ACCESS"
export const GENERAE_PRPDF_SUCCESS = "GENERAE_PRPDF_SUCCESS"
export const GENERAE_PRPDF_ERROR = "GENERAE_PRPDF_ERROR"

export const GENERAE_POPDF_ACCESS = "GENERAE_POPDF_ACCESS"
export const GENERAE_POPDF_SUCCESS = "GENERAE_POPDF_SUCCESS"
export const GENERAE_POPDF_FAILURE = "GENERAE_POPDF_ERROR"
export const GENERAE_POPDF_ERROR = "GENERAE_POPDF_ERROR"

export const GENERAE_RFQPDF_ACCESS = "GENERAE_RFQPDF_ACCESS"
export const GENERAE_RFQPDF_SUCCESS = "GENERAE_RFQPDF_SUCCESS"
export const GENERAE_RFQPDF_FAILURE = "GENERAE_RFQPDF_ERROR"
export const GENERAE_RFQPDF_ERROR = "GENERAE_RFQPDF_ERROR"

export const GENERAE_VPO_ACCESS = "GENERAE_VPO_ACCESS"
export const GENERAE_VPO_SUCCESS = "GENERAE_VPO_SUCCESS"
export const GENERAE_VPO_FAILURE = "GENERAE_VPO_FAILURE"
export const GENERAE_VPO_ERROR = "GENERAE_VPO_ERROR"

export const GENERAE_IPDF_ACCESS = "GENERAE_IPDF_ACCESS"
export const GENERAE_IPDF_SUCCESS = "GENERAE_IPDF_SUCCESS"
export const GENERAE_IPDF_FAILURE = "GENERAE_IPDF_FAILURE"
export const GENERAE_IPDF_ERROR = "GENERAE_IPDF_ERROR"

export const VENDOR_DETAILS_ACCESS = "VENDOR_DETAILS_ACCESS"
export const VENDOR_DETAILS_SUCCESS = "VENDOR_DETAILS_SUCCESS"
export const VENDOR_DETAILS_FAILURE = "VENDOR_DETAILS_FAILURE"
export const VENDOR_DETAILS_ERROR = "VENDOR_DETAILS_ERROR"

export const APPROVER_PRSEARCH_ACCESS = "APPROVER_PRSEARCH_ACCESS"
export const APPROVER_PRSEARCH_SUCCESS = "APPROVER_PRSEARCH_SUCCESS"
export const APPROVER_PRSEARCH_FAILURE = "APPROVER_PRSEARCH_FAILURE"
export const APPROVER_PRSEARCH_ERROR = "APPROVER_PRSEARCH_ERROR"

export const QUOTE_LIST_ACCESS = "QUOTE_LIST_ACCESS"
export const QUOTE_LIST_SUCCESS = "QUOTE_LIST_SUCCESS"
export const QUOTE_LIST_FAILURE = "QUOTE_LIST_FAILURE"
export const QUOTE_LIST_ERROR = "QUOTE_LIST_ERROR"

export const QUOTE_PDF_ACCESS = "QUOTE_PDF_ACCESS"
export const QUOTE_PDF_SUCCESS = "QUOTE_PDF_SUCCESS"
export const QUOTE_PDF_FAILURE = "QUOTE_PDF_FAILURE"
export const QUOTE_PDF_ERROR = "QUOTE_PDF_ERROR"

export const CPR_PRSEARCH_ACCESS = "CPR_PRSEARCH_ACCESS"
export const CPR_PRSEARCH_SUCCESS = "CPR_PRSEARCH_SUCCESS"
export const CPR_PRSEARCH_FAILURE = "CPR_PRSEARCH_FAILURE"
export const CPR_PRSEARCH_ERROR = "CPR_PRSEARCH_ERROR"

export const VENDOR_RFQ_LIST_ACCESS = "VENDOR_RFQ_LIST_ACCESS"
export const VENDOR_RFQ_LIST_SUCCESS = "VENDOR_RFQ_LIST_SUCCESS"
export const VENDOR_RFQ_LIST_FAILURE = "VENDOR_RFQ_LIST_FAILURE"
export const VENDOR_RFQ_LIST_ERROR = "VENDOR_RFQ_LIST_ERROR"

export const RFQPDF_ACCESS = "RFQPDF_ACCESS"
export const RFQPDF_SUCCESS = "RFQPDF_SUCCESS"
export const RFQPDF_FAILURE = "RFQPDF_FAILURE"
export const RFQPDF_ERROR = "RFQPDF_ERROR"

export const PO_APPROVAL_ACCESS = "PO_APPROVAL_ACCESS"
export const PO_APPROVAL_SUCCESS = "PO_APPROVAL_SUCCESS"
export const PO_APPROVAL_FAILURE = "PO_APPROVAL_FAILURE"
export const PO_APPROVAL_ERROR = "PO_APPROVAL_ERROR"

export const PO_APPROVAL_ACCESS_ALL = "PO_APPROVAL_ACCESS_ALL"
export const PO_APPROVAL_SUCCESS_ALL = "PO_APPROVAL_SUCCESS_ALL"
export const PO_APPROVAL_FAILURE_ALL = "PO_APPROVAL_FAILURE_ALL"
export const PO_APPROVAL_ERROR_ALL = "PO_APPROVAL_ERROR_ALL"


export const GET_APPO_ACCESS = "GET_APPO_ACCESS"
export const GET_APPO_SUCCESS = "GET_APPO_SUCCESS"
export const GET_APPO_FAILURE = "GET_APPO_FAILURE"
export const GET_APPO_ERROR = "GET_APPO_ERROR"

export const GET_OUT_RFQ_ACCESS = "GET_OUT_RFQ_ACCESS"
export const GET_OUT_RFQ_SUCCESS = "GET_OUT_RFQ_SUCCESS"
export const GET_OUT_RFQ_FAILURE = "GET_OUT_RFQ_FAILURE"
export const GET_OUT_RFQ_ERROR = "GET_OUT_RFQ_ERROR"

export const GET_OUT_RFQ_SUM_ACCESS = "GET_OUT_RFQ_SUM_ACCESS"
export const GET_OUT_RFQ_SUM_SUCCESS = "GET_OUT_RFQ_SUM_SUCCESS"
export const GET_OUT_RFQ_SUM_FAILURE = "GET_OUT_RFQ_SUM_FAILURE"
export const GET_OUT_RFQ_SUM_ERROR = "GET_OUT_RFQ_SUM_ERROR"

export const GET_RRFQ_PAGE_DETAILS_ACCESS = "GET_RRFQ_PAGE_DETAILS_ACCESS"
export const GET_RRFQ_PAGE_DETAILS_SUCCESS = "GET_RRFQ_PAGE_DETAILS_SUCCESS"
export const GET_RRFQ_PAGE_DETAILS_FAILURE = "GET_RRFQ_PAGE_DETAILS_FAILURE"
export const GET_RRFQ_PAGE_DETAILS_ERROR = "GET_RRFQ_PAGE_DETAILS_ERROR"

export const VEN_RFQ_OUT_ACCESS = "VEN_RFQ_OUT_ACCESS"
export const VEN_RFQ_OUT_SUCCESS = "VEN_RFQ_OUT_SUCCESS"
export const VEN_RFQ_OUT_FAILURE = "VEN_RFQ_OUT_FAILURE"
export const VEN_RFQ_OUT_ERROR = "VEN_RFQ_OUT_ERROR"

export const NEW_QUOTE_DETAILS_ACCESS = "NEW_QUOTE_DETAILS_ACCESS"
export const NEW_QUOTE_DETAILS_SUCCESS = "NEW_QUOTE_DETAILS_SUCCESS"
export const NEW_QUOTE_DETAILS_FAILURE = "NEW_QUOTE_DETAILS_FAILURE"
export const NEW_QUOTE_DETAILS_ERROR = "NEW_QUOTE_DETAILS_ERROR"

export const GL_CODE_ACCESS = "GL_CODE_ACCESS"
export const GL_CODE_SUCCESS = "GL_CODE_SUCCESS"
export const GL_CODE_FAILURE = "GL_CODE_FAILURE"
export const GL_CODE_ERROR = "GL_CODE_ERROR"

export const RFQ_QUT_LIST_ACCESS = "RFQ_QUT_LIST_ACCESS"
export const RFQ_QUT_LIST_SUCCESS = "RFQ_QUT_LIST_SUCCESS"
export const RFQ_QUT_LIST_FAILURE = "RFQ_QUT_LIST_FAILURE"
export const RFQ_QUT_LIST_ERROR = "RFQ_QUT_LIST_ERROR"

export const VIEW_RFQ_ACCESS = "VIEW_RFQ_ACCESS"
export const VIEW_RFQ_SUCCESS = "VIEW_RFQ_SUCCESS"
export const VIEW_RFQ_FAILURE = "VIEW_RFQ_FAILURE"
export const VIEW_RFQ_ERROR = "VIEW_RFQ_ERROR"

export const VIEW_QUOTATION_ACCESS = "VIEW_QUOTATION_ACCESS"
export const VIEW_QUOTATION_SUCCESS = "VIEW_QUOTATION_SUCCESS"
export const VIEW_QUOTATION_FAILURE = "VIEW_QUOTATION_FAILURE"
export const VIEW_QUOTATION_ERROR = "VIEW_QUOTATION_ERROR"

export const RFQ_VENDOR_LIST_ACCESS = "RFQ_VENDOR_LIST_ACCESS"
export const RFQ_VENDOR_LIST_SUCCESS = "RFQ_VENDOR_LIST_SUCCESS"
export const RFQ_VENDOR_LIST_FAILURE = "RFQ_VENDOR_LIST_FAILURE"
export const RFQ_VENDOR_LIST_ERROR = "RFQ_VENDOR_LIST_ERROR"

export const VIEW_LIEXP_ACCESS = "VIEW_LIEXP_ACCESS"
export const VIEW_LIEXP_SUCCESS = "VIEW_LIEXP_SUCCESS"
export const VIEW_LIEXP_FAILURE = "VIEW_LIEXP_FAILURE"
export const VIEW_LIEXP_ERROR = "VIEW_LIEXP_ERROR"

export const GPD_ACCESS = "GPD_ACCESS"
export const GPD_SUCCESS = "GPD_SUCCESS"
export const GPD_FAILURE = "GPD_FAILURE"
export const GPD_ERROR = "GPD_ERROR"

export const GPO_ACCESS = "GPO_ACCESS"
export const GPO_SUCCESS = "GPO_SUCCESS"
export const GPO_FAILURE = "GPO_FAILURE"
export const GPO_ERROR = "GPO_ERROR"

export const GPOA_ACCESS = "GPOA_ACCESS"
export const GPOA_SUCCESS = "GPOA_SUCCESS"
export const GPOA_FAILURE = "GPOA_FAILURE"
export const GPOA_ERROR = "GPOA_ERROR"

export const POSA_ACCESS = "POSA_ACCESS"
export const POSA_SUCCESS = "POSA_SUCCESS"
export const POSA_FAILURE = "POSA_FAILURE"
export const POSA_ERROR = "POSA_ERROR"

export const FREE_FROM_ACCESS = "FREE_FROM_ACCESS"
export const FREE_FROM_SUCCESS = "FREE_FROM_SUCCESS"
export const FREE_FROM_FAILURE = "FREE_FROM_FAILURE"
export const FREE_FROM_ERROR = "FREE_FROM_ERROR"

export const E2P_APPROVAL_LIST_ACCESS = "E2P_APPROVAL_LIST_ACCESS"
export const E2P_APPROVAL_LIST_SUCCESS = "E2P_APPROVAL_LIST_SUCCESS"
export const E2P_APPROVAL_LIST_FAILURE = "E2P_APPROVAL_LIST_FAILURE"
export const E2P_APPROVAL_LIST_ERROR = "E2P_APPROVAL_LIST_ERROR"

export const E2P_APPROVAL_REJ_LIST_ACCESS = "E2P_APPROVAL_REJ_LIST_ACCESS"
export const E2P_APPROVAL_REJ_LIST_SUCCESS = "E2P_APPROVAL_REJ_LIST_SUCCESS"
export const E2P_APPROVAL_REJ_LIST_FAILURE = "E2P_APPROVAL_REJ_LIST_FAILURE"
export const E2P_APPROVAL_REJ_LIST_ERROR = "E2P_APPROVAL_REJ_LIST_ERROR"


export const E2P_APPROVAL_DETAILS_ACCESS = "E2P_APPROVAL_DETAILS_ACCESS"
export const E2P_APPROVAL_DETAILS_SUCCESS = "E2P_APPROVAL_DETAILS_SUCCESS"
export const E2P_APPROVAL_DETAILS_FAILURE = "E2P_APPROVAL_DETAILS_FAILURE"
export const E2P_APPROVAL_DETAILS_ERROR = "E2P_APPROVAL_DETAILS_ERROR"

export const VENDOR_LIST_ACCESS = "VENDOR_LIST_ACCESS"
export const VENDOR_LIST_SUCCESS = "VENDOR_LIST_SUCCESS"
export const VENDOR_LIST_FAILURE = "VENDOR_LIST_FAILURE"
export const VENDOR_LIST_ERROR = "VENDOR_LIST_ERROR"

export const PO_LIST_ACCESS = "PO_LIST_ACCESS"
export const PO_LIST_SUCCESS = "PO_LIST_SUCCESS"
export const PO_LIST_CANCEL_SUCCESS = "PO_LIST_CANCEL_SUCCESS"
export const PO_LIST_ERROR = "PO_LIST_ERROR"

export const E2P_AUDIT_ACCESS = "E2P_AUDIT_ACCESS"
export const E2P_AUDIT_SUCCESS = "E2P_AUDIT_SUCCESS"
export const E2P_AUDIT_FAILURE = "E2P_AUDIT_FAILURE"
export const E2P_AUDIT_ERROR = "E2P_AUDIT_ERROR"

export const PFQPDF_LIST_ACCESS = "PFQPDF_LIST_ACCESS"
export const PFQPDF_LIST_SUCCESS = "PFQPDF_LIST_SUCCESS"
export const PFQPDF_LIST_FAILURE = "PFQPDF_LIST_FAILURE"
export const PFQPDF_LIST_ERROR = "PFQPDF_LIST_ERROR"

export const QPDF_LIST_ACCESS = "QPDF_LIST_ACCESS"
export const QPDF_LIST_SUCCESS = "QPDF_LIST_SUCCESS"
export const QPDF_LIST_FAILURE = "QPDF_LIST_FAILURE"
export const QPDF_LIST_ERROR = "QPDF_LIST_ERROR"

export const VIEW_PO_ACCESS = "VIEW_PO_ACCESS"
export const VIEW_PO_SUCCESS = "VIEW_PO_SUCCESS"
export const VIEW_PO_FAILURE = "VIEW_PO_FAILURE"
export const VIEW_PO_ERROR = "VIEW_PO_ERROR"

export const PREVIEW_DO_ACCESS = "PREVIEW_DO_ACCESS"
export const PREVIEW_DO_SUCCESS = "PREVIEW_DO_SUCCESS"
export const PREVIEW_DO_FAILURE = "PREVIEW_DO_FAILURE"
export const PREVIEW_DO_ERROR = "PREVIEW_DO_ERROR"

export const PO_LINE_ACCESS = "PO_LINE_ACCESS"
export const PO_LINE_SUCCESS = "PO_LINE_SUCCESS"
export const PO_LINE_FAILURE = "PO_LINE_FAILURE"
export const PO_LINE_ERROR = "PO_LINE_ERROR"

export const PO_LINE_DETAILS_ACCESS = "PO_LINE_DETAILS_ACCESS"
export const PO_LINE_DETAILS_SUCCESS = "PO_LINE_DETAILS_SUCCESS"
export const PO_LINE_DETAILS_FAILURE = "PO_LINE_DETAILS_FAILURE"
export const PO_LINE_DETAILS_ERROR = "PO_LINE_DETAILS_ERROR"


export const PREVIEW_GRN_ACCESS = "PREVIEW_GRN_ACCESS"
export const PREVIEW_GRN_SUCCESS = "PREVIEW_GRN_SUCCESS"
export const PREVIEW_GRN_FAILURE = "PREVIEW_GRN_FAILURE"
export const PREVIEW_GRN_ERROR = "PREVIEW_GRN_ERROR"

export const PO_DETAILS_ACCESS = "PO_DETAILS_ACCESS"
export const PO_DETAILS_SUCCESS = "PO_DETAILS_SUCCESS"
export const PO_DETAILS_FAILURE = "PO_DETAILS_FAILURE"
export const PO_DETAILS_ERROR = "PO_DETAILS_ERROR"

export const REQ_ADD_ITEM_ACCESS = "REQ_ADD_ITEM_ACCESS"
export const REQ_ADD_ITEM_SUCCESS = "REQ_ADD_ITEM_SUCCESS"
export const REQ_ADD_ITEM_FAILURE = "REQ_ADD_ITEM_FAILURE"
export const REQ_ADD_ITEM_ERROR = "REQ_ADD_ITEM_ERROR"

export const DELETE_PURCHASE_ORDER_DATA = "DELETE_PURCHASE_ORDER_DATA"
export const DELETE_PURCHASE_ORDER_DEFAULT = "DELETE_PURCHASE_ORDER_DEFAULT"

export const E2P_FIN_LIST_ACCESS = "E2P_FIN_LIST_ACCESS"
export const E2P_FIN_LIST_SUCCESS = "E2P_FIN_LIST_SUCCESS"
export const E2P_FIN_LIST_FAILURE = "E2P_FIN_LIST_FAILURE"
export const E2P_FIN_LIST_ERROR = "E2P_FIN_LIST_ERROR"

export const REQ_CON_ITEM_ACCESS = "REQ_CON_ITEM_ACCESS"
export const REQ_CON_ITEM_SUCCESS = "REQ_CON_ITEM_SUCCESS"
export const REQ_CON_ITEM_FAILURE = "REQ_CON_ITEM_FAILURE"
export const REQ_CON_ITEM_ERROR = "REQ_CON_ITEM_ERROR"

export const E2P_POP_TAX_ACCESS = "E2P_POP_TAX_ACCESS"
export const E2P_POP_TAX_SUCCESS = "E2P_POP_TAX_SUCCESS"
export const E2P_POP_TAX_FAILURE = "E2P_POP_TAX_FAILURE"
export const E2P_POP_TAX_ERROR = "E2P_POP_TAX_ERROR"

export const E2P_WITH_TAX_ACCESS = "E2P_WITH_TAX_ACCESS"
export const E2P_WITH_TAX_SUCCESS = "E2P_WITH_TAX_SUCCESS"
export const E2P_WITH_TAX_FAILURE = "E2P_WITH_TAX_FAILURE"
export const E2P_WITH_TAX_ERROR = "E2P_WITH_TAX_ERROR"

export const E2P_PAY_FOR_ACCESS = "E2P_PAY_FOR_ACCESS"
export const E2P_PAY_FOR_SUCCESS = "E2P_PAY_FOR_SUCCESS"
export const E2P_PAY_FOR_FAILURE = "E2P_PAY_FOR_FAILURE"
export const E2P_PAY_FOR_ERROR = "E2P_PAY_FOR_ERROR"

export const REQ_DOC_LIST_ACCESS = "REQ_DOC_LIST_ACCESS"
export const REQ_DOC_LIST_SUCCESS = "REQ_DOC_LIST_SUCCESS"
export const REQ_DOC_LIST_FAILURE = "REQ_DOC_LIST_FAILURE"
export const REQ_DOC_LIST_ERROR = "REQ_DOC_LIST_ERROR"

export const REQ_APROV_DET_ACCESS = "REQ_APROV_DET_ACCESS"
export const REQ_APROV_DET_SUCCESS = "REQ_APROV_DET_SUCCESS"
export const REQ_APROV_DET_FAILURE = "REQ_APROV_DET_FAILURE"
export const REQ_APROV_DET_ERROR = "REQ_APROV_DET_ERROR"

export const E2P_PENDING_FYFA_ACCESS = "E2P_PENDING_FYFA_ACCESS"
export const E2P_PENDING_FYFA_SUCCESS = "E2P_PENDING_FYFA_SUCCESS"
export const E2P_PENDING_FYFA_FAILURE = "E2P_PENDING_FYFA_FAILURE"
export const E2P_PENDING_FYFA_ERROR = "E2P_PENDING_FYFA_ERROR"

export const REQ_INVOICE_TEMPLATE_ACCESS = "REQ_INVOICE_TEMPLATE_ACCESS"
export const REQ_INVOICE_TEMPLATE_SUCCESS = "REQ_INVOICE_TEMPLATE_SUCCESS"
export const REQ_INVOICE_TEMPLATE_FAILURE = "REQ_INVOICE_TEMPLATE_FAILURE"
export const REQ_INVOICE_TEMPLATE_ERROR = "REQ_INVOICE_TEMPLATE_ERROR"

export const DOC_ENQ_ACCESS = "DOC_ENQ_ACCESS"
export const DOC_ENQ_SUCCESS = "DOC_ENQ_SUCCESS"
export const DOC_ENQ_FAILURE = "DOC_ENQ_FAILURE"
export const DOC_ENQ_ERROR = "DOC_ENQ_ERROR"

export const REQ_INVOICE_ACCESS = "REQ_INVOICE_ACCESS"
export const REQ_INVOICE_SUCCESS = "REQ_INVOICE_SUCCESS"
export const REQ_INVOICE_FAILURE = "REQ_INVOICE_FAILURE"
export const REQ_INVOICE_ERROR = "REQ_INVOICE_ERROR"

export const E2P_CAN_APPROVE_ACCESS = "E2P_CAN_APPROVE_ACCESS"
export const E2P_CAN_APPROVE_SUCCESS = "E2P_CAN_APPROVE_SUCCESS"
export const E2P_CAN_APPROVE_FAILURE = "E2P_CAN_APPROVE_FAILURE"
export const E2P_CAN_APPROVE_ERROR = "E2P_CAN_APPROVE_ERROR"

export const DASHBOARD_ACCESS = "DASHBOARD_ACCESS"
export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS"
export const DASHBOARD_FAILURE = "DASHBOARD_FAILURE"
export const DASHBOARD_ERROR = "DASHBOARD_ERROR"

export const CN_LISTING_ACCESS = "CN_LISTING_ACCESS"
export const CN_LISTING_SUCCESS = "CN_LISTING_SUCCESS"
export const CN_LISTING_FAILURE = "CN_LISTING_FAILURE"
export const CN_LISTING_ERROR = "CN_LISTING_ERROR"

export const DN_LISTING_ACCESS = "DN_LISTING_ACCESS"
export const DN_LISTING_SUCCESS = "DN_LISTING_SUCCESS"
export const DN_LISTING_FAILURE = "DN_LISTING_FAILURE"
export const DN_LISTING_ERROR = "DN_LISTING_ERROR"

export const CN_DETAILS_ACCESS = "CN_DETAILS_ACCESS"
export const CN_DETAILS_SUCCESS = "CN_DETAILS_SUCCESS"
export const CN_DETAILS_FAILURE = "CN_DETAILS_FAILURE"
export const CN_DETAILS_ERROR = "CN_DETAILS_ERROR"

export const DN_DETAILS_ACCESS = "DN_DETAILS_ACCESS"
export const DN_DETAILS_SUCCESS = "DN_DETAILS_SUCCESS"
export const DN_DETAILS_FAILURE = "DN_DETAILS_FAILURE"
export const DN_DETAILS_ERROR = "DN_DETAILS_ERROR"

export const CN_TRACKING_ACK_ACCESS = "CN_TRACKING_ACK_ACCESS"
export const CN_TRACKING_ACK_SUCCESS = "CN_TRACKING_ACK_SUCCESS"
export const CN_TRACKING_ACK_FAILURE = "CN_TRACKING_ACK_FAILURE"
export const CN_TRACKING_ACK_ERROR = "CN_TRACKING_ACK_ERROR"

export const CN_TRACKING_ACCESS = "CN_TRACKING_ACCESS"
export const CN_TRACKING_SUCCESS = "CN_TRACKING_SUCCESS"
export const CN_TRACKING_FAILURE = "CN_TRACKING_FAILURE"
export const CN_TRACKING_ERROR = "CN_TRACKING_ERROR"

export const CN_TRACKING_DETAILS_ACCESS = "CN_TRACKING_DETAILS_ACCESS"
export const CN_TRACKING_DETAILS_SUCCESS = "CN_TRACKING_DETAILS_SUCCESS"
export const CN_TRACKING_DETAILS_FAILURE = "CN_TRACKING_DETAILS_FAILURE"
export const CN_TRACKING_DETAILS_ERROR = "CN_TRACKING_DETAILS_ERROR"

export const DN_TRACKING_DETAILS_ACCESS = "DN_TRACKING_DETAILS_ACCESS"
export const DN_TRACKING_DETAILS_SUCCESS = "DN_TRACKING_DETAILS_SUCCESS"
export const DN_TRACKING_DETAILS_FAILURE = "DN_TRACKING_DETAILS_FAILURE"
export const DN_TRACKING_DETAILS_ERROR = "DN_TRACKING_DETAILS_ERROR"

export const DN_TRACKING_ACCESS = "DN_TRACKING_ACCESS"
export const DN_TRACKING_SUCCESS = "DN_TRACKING_SUCCESS"
export const DN_TRACKING_SUCCESS_NEW = "DN_TRACKING_SUCCESS_NEW"
export const DN_TRACKING_SUCCESS_S = "DN_TRACKING_SUCCESS_S"
export const DN_TRACKING_SUCCESS_PAID = "DN_TRACKING_SUCCESS_PAID"
export const DN_TRACKING_FAILURE = "DN_TRACKING_FAILURE"
export const DN_TRACKING_ERROR = "DN_TRACKING_ERROR"

export const GENERAE_DEBITPDF_ACCESS = "GENERAE_DEBITPDF_ACCESS"
export const GENERAE_DEBITPDF_SUCCESS = "GENERAE_DEBITPDF_SUCCESS"
export const GENERAE_DEBITPDF_FAILURE = "GENERAE_DEBITPDF_FAILURE"
export const GENERAE_DEBITPDF_ERROR = "GENERAE_DEBITPDF_ERROR"

export const GENERAE_CREDITPDF_ACCESS = "GENERAE_CREDITPDF_ACCESS"
export const GENERAE_CREDITPDF_SUCCESS = "GENERAE_CREDITPDF_SUCCESS"
export const GENERAE_CREDITPDF_FAILURE = "GENERAE_CREDITPDF_FAILURE"
export const GENERAE_CREDITPDF_ERROR = "GENERAE_CREDITPDF_ERROR"

export const CNDN_INVOICE_ACCESS = "CNDN_INVOICE_ACCESS"
export const CNDN_INVOICE_SUCCESS = "CNDN_INVOICE_SUCCESS"
export const CNDN_INVOICE_FAILURE = "CNDN_INVOICE_FAILURE"
export const CNDN_INVOICE_ERROR = "CNDN_INVOICE_ERROR"

export const CRPDF_ACCESS = "CRPDF_ACCESS"
export const CRPDF_SUCCESS = "CRPDF_SUCCESS"
export const CRPDF_FAILURE = "CRPDF_FAILURE"
export const CRPDF_ERROR = "CRPDF_ERROR"

export const CANCEL_PR_LIST_ACCESS = "CANCEL_PR_LIST_ACCESS"
export const CANCEL_PR_LIST_SUCCESS = "CANCEL_PR_LIST_SUCCESS"
export const CANCEL_PR_LIST_FAILURE = "CANCEL_PR_LIST_FAILURE"
export const CANCEL_PR_LIST_ERROR = "CANCEL_PR_LIST_ERROR"

export const ED_POLICY_ACCESS = "ED_POLICY_ACCESS"
export const ED_POLICY_SUCCESS = "ED_POLICY_SUCCESS"
export const ED_POLICY_FAILURE = "ED_POLICY_FAILURE"
export const ED_POLICY_ERROR = "ED_POLICY_ERROR"

export const UG_LIST_ACCESS = "UG_LIST_ACCESS"
export const UG_LIST_SUCCESS = "UG_LIST_SUCCESS"
export const UG_LIST_FAILURE = "UG_LIST_FAILURE"
export const UG_LIST_ERROR = "UG_LIST_ERROR"

export const FR_ACCESS = "FR_ACCESS"
export const FR_SUCCESS = "FR_SUCCESS"
export const FR_FAILURE = "FR_FAILURE"
export const FR_ERROR = "FR_ERROR"

export const APP_PACK_ACCESS = "APP_PACK_ACCESS"
export const APP_PACK_SUCCESS = "APP_PACK_SUCCESS"
export const APP_PACK_FAILURE = "APP_PACK_FAILURE"
export const APP_PACK_ERROR = "APP_PACK_ERROR"

export const UGD_ACCESS = "UGD_ACCESS"
export const UGD_SUCCESS = "UGD_SUCCESS"
export const UGD_FAILURE = "UGD_FAILURE"
export const UGD_ERROR = "UGD_ERROR"

export const DL_ACCESS = "DASHBOARD_LIST_ACCESS"
export const DL_SUCCESS = "DASHBOARD_LIST_SUCCESS"
export const DL_MX_SUCCESS = "DASHBOARD_MATIX_LIST_SUCCESS"
export const DL_LST_SUCCESS = "DASHBOARD_LISTING_LIST_SUCCESS"
export const DL_FAILURE = "DASHBOARD_LIST_FAILURE"
export const DL_ERROR = "DASHBOARD_LIST_ERROR"

export const COUNTRY_ACCESS = "COUNTRY_ACCESS"
export const COUNTRY_SUCCESS = "COUNTRY_SUCCESS"
export const COUNTRY_FAILURE = "COUNTRY_FAILURE"
export const COUNTRY_ERROR = "COUNTRY_ERROR"

export const STATE_ACCESS = "STATE_ACCESS"
export const STATE_SUCCESS = "STATE_SUCCESS"
export const STATE_FAILURE = "STATE_FAILURE"
export const STATE_ERROR = "STATE_ERROR"

export const HOLIDAY_LIST_ACCESS = "HOLIDAY_LIST_ACCESS"
export const HOLIDAY_LIST_SUCCESS = "HOLIDAY_LIST_SUCCESS"
export const HOLIDAY_LIST_FAILURE = "HOLIDAY_LIST_FAILURE"
export const HOLIDAY_LIST_ERROR = "HOLIDAY_LIST_ERROR"

export const TAXCODE_LIST_ACCESS = "TAXCODE_LIST_ACCESS"
export const TAXCODE_LIST_SUCCESS = "TAXCODE_LIST_SUCCESS"
export const TAXCODE_LIST_FAILURE = "TAXCODE_LIST_FAILURE"
export const TAXCODE_LIST_ERROR = "TAXCODE_LIST_ERROR"

export const TAXCODE_RATE_ACCESS = "TAXCODE_RATE_ACCESS"
export const TAXCODE_RATE_SUCCESS = "TAXCODE_RATE_SUCCESS"
export const TAXCODE_RATE_FAILURE = "TAXCODE_RATE_FAILURE"
export const TAXCODE_RATE_ERROR = "TAXCODE_RATE_ERROR"

export const COMPANY_LIST_ACCESS = "COMPANY_LIST_ACCESS"
export const COMPANY_LIST_SUCCESS = "COMPANY_LIST_SUCCESS"
export const COMPANY_LIST_FAILURE = "COMPANY_LIST_FAILURE"
export const COMPANY_LIST_ERROR = "COMPANY_LIST_ERROR"

export const VENDOR_MAP_ACCESS = "VENDOR_MAP_ACCESS"
export const VENDOR_MAP_SUCCESS = "VENDOR_MAP_SUCCESS"
export const VENDOR_MAP_FAILURE = "VENDOR_MAP_FAILURE"
export const VENDOR_MAP_ERROR = "VENDOR_MAP_ERROR"

export const USER_ACCOUNT_ACCESS = "USER_ACCOUNT_ACCESS"
export const USER_ACCOUNT_SUCCESS = "USER_ACCOUNT_SUCCESS"
export const USER_ACCOUNT_FAILURE = "USER_ACCOUNT_FAILURE"
export const USER_ACCOUNT_ERROR = "USER_ACCOUNT_ERROR"

export const USER_VALIDATE_ACCESS = "USER_VALIDATE_ACCESS"
export const USER_VALIDATE_SUCCESS = "USER_VALIDATE_SUCCESS"
export const USER_VALIDATE_FAILURE = "USER_VALIDATE_FAILURE"
export const USER_VALIDATE_ERROR = "USER_VALIDATE_ERROR"

export const MATRIX_LIST_ACCESS = "MATRIX_LIST_ACCESS"
export const MATRIX_LIST_SUCCESS = "MATRIX_LIST_SUCCESS"
export const MATRIX_LIST_FAILURE = "MATRIX_LIST_FAILURE"
export const MATRIX_LIST_ERROR = "MATRIX_LIST_ERROR"


export const CURRENCY_ACCESS = "CURRENCY_ACCESS"
export const CURRENCY_SUCCESS = "CURRENCY_SUCCESS"
export const CURRENCY_FAILURE = "CURRENCY_FAILURE"
export const CURRENCY_ERROR = "CURRENCY_ERROR"

export const REPORT_LIST_ACCESS = "REPORT_LIST_ACCESS"
export const REPORT_LIST_SUCCESS = "REPORT_LIST_SUCCESS"
export const REPORT_LIST_FAILURE = "REPORT_LIST_FAILURE"
export const REPORT_LIST_ERROR = "REPORT_LIST_ERROR"

export const PAYMENT_TERM_ACCESS = "PAYMENT_TERM_ACCESS"
export const PAYMENT_TERM_SUCCESS = "PAYMENT_TERM_SUCCESS"
export const PAYMENT_TERM_FAILURE = "PAYMENT_TERM_FAILURE"
export const PAYMENT_TERM_ERROR = "PAYMENT_TERM_ERROR"

export const PAYMENT_METHOD_ACCESS = "PAYMENT_METHOD_ACCESS"
export const PAYMENT_METHOD_SUCCESS = "PAYMENT_METHOD_SUCCESS"
export const PAYMENT_METHOD_FAILURE = "PAYMENT_METHOD_FAILURE"
export const PAYMENT_METHOD_ERROR = "PAYMENT_METHOD_ERROR"

export const MULTIPLE_VENDOR_ACCESS = "MULTIPLE_VENDOR_ACCESS"
export const MULTIPLE_VENDOR_SUCCESS = "MULTIPLE_VENDOR_SUCCESS"
export const MULTIPLE_VENDOR_FAILURE = "MULTIPLE_VENDOR_FAILURE"
export const MULTIPLE_VENDOR_ERROR = "MULTIPLE_VENDOR_ERROR"

export const FILL_GST_ACCESS = "FILL_GST_ACCESS"
export const FILL_GST_SUCCESS = "FILL_GST_SUCCESS"
export const FILL_GST_FAILURE = "FILL_GST_FAILURE"
export const FILL_GST_ERROR = "FILL_GST_ERROR"

export const FILL_TAX_ACCESS = "FILL_TAX_ACCESS"
export const FILL_TAX_SUCCESS = "FILL_TAX_SUCCESS"
export const FILL_TAX_FAILURE = "FILL_TAX_FAILURE"
export const FILL_TAX_ERROR = "FILL_TAX_ERROR"

export const CHNAGE_PASS_ACCESS = "CHNAGE_PASS_ACCESS"
export const CHNAGE_PASS_SUCCESS = "CHNAGE_PASS_SUCCESS"
export const CHNAGE_PASS_FAILURE = "CHNAGE_PASS_FAILURE"
export const CHNAGE_PASS_ERROR = "CHNAGE_PASS_ERROR"

export const BUDGET_AMOUNT_ACCESS = "BUDGET_AMOUNT_ACCESS"
export const BUDGET_AMOUNT_SUCCESS = "BUDGET_AMOUNT_SUCCESS"
export const BUDGET_AMOUNT_FAILURE = "BUDGET_AMOUNT_FAILURE"
export const BUDGET_AMOUNT_ERROR = "BUDGET_AMOUNT_ERROR"


export const INV_FUND_ACCESS = "INV_FUND_ACCESS"
export const INV_FUND_SUCCESS = "INV_FUND_SUCCESS"
export const INV_FUND_FAILURE = "INV_FUND_FAILURE"
export const INV_FUND_ERROR = "INV_FUND_ERROR"

export const VENDOR_BILL_DETAILS_ACCESS = "VENDOR_BILL_DETAILS_ACCESS"
export const VENDOR_BILL_DETAILS_SUCCESS = "VENDOR_BILL_DETAILS_SUCCESS"
export const VENDOR_BILL_DETAILS_FAILURE = "VENDOR_BILL_DETAILS_FAILURE"
export const VENDOR_BILL_DETAILS_ERROR = "VENDOR_BILL_DETAILS_ERROR"

export const FILL_TAX_CODE_ACCESS = "FILL_TAX_CODE_ACCESS"
export const FILL_TAX_CODE_SUCCESS = "FILL_TAX_CODE_SUCCESS"
export const FILL_TAX_CODE_FAILURE = "FILL_TAX_CODE_FAILURE"
export const FILL_TAX_CODE_ERROR = "FILL_TAX_CODE_ERROR"

export const VERIFIED_ACCESS = "VERIFIED_ACCESS"
export const VERIFIED_SUCCESS = "VERIFIED_SUCCESS"
export const VERIFIED_FAILURE = "VERIFIED_FAILURE"
export const VERIFIED_ERROR = "VERIFIED_ERROR"

export const PENDING_FYFA_ACCESS = "PENDING_FYFA_ACCESS"
export const PENDING_FYFA_SUCCESS = "PENDING_FYFA_SUCCESS"
export const PENDING_FYFA_FAILURE = "PENDING_FYFA_FAILURE"
export const PENDING_FYFA_ERROR = "PENDING_FYFA_ERROR"

export const VENDOR_DETAIL_ACCESS = "VENDOR_DETAIL_ACCESS"
export const VENDOR_DETAIL_SUCCESS = "VENDOR_DETAIL_SUCCESS"
export const VENDOR_DETAIL_FAILURE = "VENDOR_DETAIL_FAILURE"
export const VENDOR_DETAIL_ERROR = "VENDOR_DETAIL_ERROR"

export const PO_TRACKING_ACCESS = "PO_TRACKING_ACCESS"
export const PO_TRACKING_SUCCESS = "PO_TRACKING_SUCCESS"
export const PO_TRACKING_FAILURE = "PO_TRACKING_FAILURE"
export const PO_TRACKING_ERROR = "PO_TRACKING_ERROR"
export const PO_TRACKING_CANCEL = "PO_TRACKING_CANCEL"

export const TRANS_TRACKING_ACCESS = "TRANS_TRACKING_ACCESS"
export const TRANS_TRACKING_SUCCESS = "TRANS_TRACKING_SUCCESS"
export const TRANS_TRACKING_FAILURE = "TRANS_TRACKING_FAILURE"
export const TRANS_TRACKING_ERROR = "TRANS_TRACKING_ERROR"
export const TRANS_TRACKING_CANCEL = "TRANS_TRACKING_CANCEL"